In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("../data/processed/delivery_data_features.csv")

print(df.shape)

(142502, 41)

In [2]:
top_source_hubs = (
    df.groupby("source_center")
      .size()
      .reset_index(name="shipments")
      .sort_values("shipments", ascending=False)
)

top_source_hubs.head(10)

     source_center  shipments
8     IND000000ACB      23279
921   IND562132AAA       9907
605   IND421302AAG       9012
568   IND411033AAA       4021
753   IND501359AAE       3336
1224  IND712311AAA       2591
136   IND160002AAC       2422
512   IND395023AAA       2182
28    IND110037AAM       2000
908   IND560099AAB       1924

In [3]:
top_destination_hubs = (
    df.groupby("destination_center")
      .size()
      .reset_index(name="shipments")
      .sort_values("shipments", ascending=False)
)

top_destination_hubs.head(10)

     destination_center  shipments
6          IND000000ACB      15117
911        IND562132AAA      10961
601        IND421302AAG       5411
747        IND501359AAE       5124
1205       IND712311AAA       4852
25         IND110037AAM       3757
563        IND411033AAA       3666
135        IND160002AAC       2854
79         IND131028AAB       2769
1295       IND751002AAB       2515

In [4]:
top_source_hubs.head(20).to_csv(
    "../reports/top_source_hubs.csv",
    index=False
)

top_destination_hubs.head(20).to_csv(
    "../reports/top_destination_hubs.csv",
    index=False
)

print("Hub reports saved.")

Hub reports saved.

In [5]:
top_corridors = (
    df.groupby("corridor")
      .size()
      .reset_index(name="shipments")
      .sort_values("shipments", ascending=False)
)

top_corridors.head(10)

                        corridor  shipments
59    IND000000ACB->IND562132AAA       4970
1753  IND562132AAA->IND000000ACB       3316
61    IND000000ACB->IND712311AAA       2831
57    IND000000ACB->IND501359AAE       1638
54    IND000000ACB->IND421302AAG       1616
1142  IND421302AAG->IND000000ACB       1268
2511  IND781018AAB->IND110037AAM       1137
1168  IND421302AAG->IND562132AAA       1129
53    IND000000ACB->IND411033AAA       1120
60    IND000000ACB->IND600056AAB       1014

In [6]:
top_corridors.head(20).to_csv(
    "../reports/top_corridors.csv",
    index=False
)

print("Top corridor report saved.")

Top corridor report saved.

In [7]:
corridor_delay = (
    df.groupby("corridor")
      .agg({
          "segment_actual_time": "mean",
          "segment_osrm_time": "mean"
      })
      .reset_index()
)

corridor_delay["avg_delay"] = (
    corridor_delay["segment_actual_time"]
    - corridor_delay["segment_osrm_time"]
)

corridor_delay = corridor_delay.sort_values(
    "avg_delay",
    ascending=False
)

corridor_delay.head(10)

,corridor,segment_actual_time,segment_osrm_time,avg_delay
2347,IND722140AAA->IND723130AAA,1320.000000,69.000000,1251.00
2431,IND743270AAA->IND712311AAA,1133.600000,73.800000,1059.80
1222,IND425412AAA->IND424006AAA,1093.000000,79.000000,1014.00
1208,IND424304AAC->IND424006AAA,926.000000,41.500000,884.50
1218,IND425409AAA->IND424006AAA,894.000000,74.000000,820.00
1373,IND493445AAB->IND490023AAA,879.000000,61.000000,818.00
2400,IND741201AAC->IND712311AAA,865.250000,57.000000,808.25
2349,IND722151AAA->IND723130AAA,744.400000,56.600000,687.80
1213,IND425405AAA->IND424006AAA,703.388889,36.388889,667.00
1207,IND424201AAA->IND424006AAA,707.000000,67.000000,640.00

In [8]:
corridor_delay.head(20).to_csv(
    "../reports/delay_hotspots.csv",
    index=False
)

print("Delay hotspot report saved.")

Delay hotspot report saved.

In [9]:
hub_delay = (
    df.groupby("destination_center")
      .agg({
          "segment_actual_time": "mean",
          "segment_osrm_time": "mean"
      })
      .reset_index()
)

hub_delay["avg_delay"] = (
    hub_delay["segment_actual_time"]
    - hub_delay["segment_osrm_time"]
)

hub_delay = hub_delay.sort_values(
    "avg_delay",
    ascending=False
)

hub_delay.head(10)

     destination_center  segment_actual_time  segment_osrm_time   avg_delay
724        IND490023AAA           879.000000          61.000000  818.000000
219        IND221401AAA           585.000000          35.000000  550.000000
1385       IND796009AAA           376.875000          48.625000  328.250000
112        IND145001AAA           350.846154          56.897436  293.948718
687        IND473226AAA           316.685714          38.885714  277.800000
617        IND424006AAA           299.380952          25.079365  274.301587
158        IND176310AAA           331.000000          68.300000  262.700000
1300       IND754103AAA           275.727273          26.090909  249.636364
223        IND222136AAA           256.333333          17.666667  238.666667
329        IND282005AAA           252.333333          13.833333  238.500000

In [10]:
hub_delay.head(20).to_csv(
    "../reports/hub_delay_hotspots.csv",
    index=False
)

print("Hub delay report saved.")

Hub delay report saved.

In [11]:
route_summary = (
    df.groupby("route_type")
      .agg({
          "segment_actual_time": "mean",
          "segment_osrm_time": "mean",
          "segment_osrm_distance": "mean"
      })
      .reset_index()
)

route_summary["avg_delay"] = (
    route_summary["segment_actual_time"]
    - route_summary["segment_osrm_time"]
)

route_summary

,route_type,segment_actual_time,segment_osrm_time,segment_osrm_distance,avg_delay
0,Carting,25.291265,10.918306,11.875319,14.372959
1,FTL,41.828620,22.300100,28.205510,19.528520

In [12]:
route_summary.to_csv(
    "../reports/route_type_summary.csv",
    index=False
)

print("Route summary saved.")

Route summary saved.

In [13]:
bottlenecks = (
    corridor_delay.copy()
)

bottlenecks["bottleneck_score"] = (
    bottlenecks["avg_delay"]
    * bottlenecks["segment_actual_time"]
)

bottlenecks = bottlenecks.sort_values(
    "bottleneck_score",
    ascending=False
)

bottlenecks.head(10)

,corridor,segment_actual_time,segment_osrm_time,avg_delay,bottleneck_score
2347,IND722140AAA->IND723130AAA,1320.000000,69.000000,1251.00,1.651320e+06
2431,IND743270AAA->IND712311AAA,1133.600000,73.800000,1059.80,1.201389e+06
1222,IND425412AAA->IND424006AAA,1093.000000,79.000000,1014.00,1.108302e+06
1208,IND424304AAC->IND424006AAA,926.000000,41.500000,884.50,8.190470e+05
1218,IND425409AAA->IND424006AAA,894.000000,74.000000,820.00,7.330800e+05
1373,IND493445AAB->IND490023AAA,879.000000,61.000000,818.00,7.190220e+05
2400,IND741201AAC->IND712311AAA,865.250000,57.000000,808.25,6.993383e+05
2349,IND722151AAA->IND723130AAA,744.400000,56.600000,687.80,5.119983e+05
1213,IND425405AAA->IND424006AAA,703.388889,36.388889,667.00,4.691604e+05
1207,IND424201AAA->IND424006AAA,707.000000,67.000000,640.00,4.524800e+05

In [14]:
bottlenecks.head(20).to_csv(
    "../reports/bottleneck_corridors.csv",
    index=False
)

print("Bottleneck report saved.")

Bottleneck report saved.

In [15]:
import os

print(sorted(os.listdir("../reports")))

['bottleneck_corridors.csv', 'delay_hotspots.csv', 'hub_delay_hotspots.csv', 'model_comparison.csv', 'route_type_summary.csv', 'top_corridors.csv', 'top_destination_hubs.csv', 'top_source_hubs.csv']