In [1]:
import pandas as pd
import networkx as nx
import numpy as np

pd.set_option("display.max_columns", None)

df = pd.read_csv("../data/processed/delivery_data_features.csv")

print(df.shape)

(142502, 41)

In [2]:
G = nx.from_pandas_edgelist(
    df,
    source="source_center",
    target="destination_center",
    create_using=nx.DiGraph()
)

print("Nodes:", G.number_of_nodes())
print("Edges:", G.number_of_edges())

Nodes: 1657
Edges: 2783

In [3]:
degree_centrality = nx.degree_centrality(G)

degree_df = pd.DataFrame(
    degree_centrality.items(),
    columns=["hub", "degree_centrality"]
)

degree_df = degree_df.sort_values(
    "degree_centrality",
    ascending=False
)

degree_df.head(10)

              hub  degree_centrality
43   IND000000ACB           0.056763
7    IND562132AAA           0.042874
65   IND160002AAC           0.036836
3    IND421302AAG           0.035024
81   IND501359AAE           0.034420
123  IND712311AAA           0.027778
136  IND110037AAM           0.027174
4    IND411033AAA           0.025966
21   IND131028AAB           0.024155
25   IND600056AAB           0.021739

In [4]:
degree_df.head(20).to_csv(
    "../reports/degree_centrality_hubs.csv",
    index=False
)

print("Degree centrality report saved.")

Degree centrality report saved.

In [5]:
betweenness = nx.betweenness_centrality(
    G,
    k=200,
    seed=42
)

betweenness_df = pd.DataFrame(
    betweenness.items(),
    columns=["hub", "betweenness_centrality"]
)

betweenness_df = betweenness_df.sort_values(
    "betweenness_centrality",
    ascending=False
)

betweenness_df.head(10)

              hub  betweenness_centrality
43   IND000000ACB                0.225262
7    IND562132AAA                0.131562
123  IND712311AAA                0.089378
81   IND501359AAE                0.088279
3    IND421302AAG                0.075377
4    IND411033AAA                0.050304
65   IND160002AAC                0.049084
21   IND131028AAB                0.044307
114  IND781018AAB                0.043991
25   IND600056AAB                0.042687

In [6]:
betweenness_df.head(20).to_csv(
    "../reports/betweenness_centrality_hubs.csv",
    index=False
)

print("Betweenness report saved.")

Betweenness report saved.

In [7]:
network_summary = pd.DataFrame({
    "Metric": [
        "Nodes",
        "Edges"
    ],
    "Value": [
        G.number_of_nodes(),
        G.number_of_edges()
    ]
})

network_summary

  Metric  Value
0  Nodes   1657
1  Edges   2783

In [8]:
network_summary.to_csv(
    "../reports/network_summary.csv",
    index=False
)

print("Network summary saved.")

Network summary saved.

In [9]:
import os

print(sorted(os.listdir("../reports")))

['betweenness_centrality_hubs.csv', 'bottleneck_corridors.csv', 'degree_centrality_hubs.csv', 'delay_hotspots.csv', 'hub_delay_hotspots.csv', 'model_comparison.csv', 'network_summary.csv', 'route_type_summary.csv', 'top_corridors.csv', 'top_destination_hubs.csv', 'top_source_hubs.csv']